[project]
name = "autocopr"
dependencies = ["requests"]
requires-python = ">= 3.13"

[project.optional-dependencies]
# Used to create/update requirements.txt
dev = ["pip-tools"]

[tool.pip-tools]
generate-hashes = true

# Sort imports with ruff
[tool.ruff.lint]
extend-select = ["I"]
