name: Self-test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  update:
    name: self-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      # Check out the specs to run this on
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          repository: aidandenlinger/autocopr-specs
          path: './autocopr-specs'
          persist-credentials: false

      # Run the action from THIS branch on autocopr-specs in dry-run mode
      - uses: ./
        with:
          mode: "dry-run"
          root_loc: "autocopr-specs"
          verbose: "true"
